# Generated by Django 3.1 on 2022-02-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='post',
        ),
    ]
