# Generated by Django 3.1 on 2022-02-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0002_auto_20220201_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
