# Generated by Django 3.1 on 2022-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0002_auto_20220201_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='post_image',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
